<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Admin_model');
        $this->load->model('Tiket_model');
    } 

    /*
     * Listing of admin
     */
    function index()
    {
        $login = array(
                'isLogin' => $this->session->userdata('isLogin'),
                'id_pengguna' => $this->session->userdata('id_pengguna'),
                'nama' => $this->session->userdata('nama'),
                'role' => $this->session->userdata('role'),
                 );
        $data['login'] = $login;
        $data['pemesanan'] = $this->Admin_model->getpesanan();
        $this->load->view('admin/header',$data);
        $this->load->view('admin/admin', $data);
    }

    function Menutiket()
    {
       
        $data['tiket'] = $this->Tiket_model->get_tiketjoin();
        $this->load->view('admin/header');
        $this->load->view('admin/datatiket', $data);
    }

    function Menubis()
    {
        $data['bus'] = $this->Admin_model->getBus();
        $this->load->view('admin/header');
        $this->load->view('admin/databis', $data);
    }

    function konfirmasi()
    {
        $id = array(
            'kd_pesan' => $this->input->post('kd_pesan')
        );

        $data = $this->Admin_model->konfirmpesan($id);
        echo json_encode($data);
    }

    function hapusTiket(){
        $dataCari = array(
            'kd_tiket' => $this->input->post('kd_tiket')
        );
        $data = $this->Admin_model->deletetiket($dataCari);
        echo json_encode($data);

    }

    function edittiket(){

        $dataKode = array(
                        'kd_tiket' => $this->session->userdata('kd_tiket'),
                        'kd_bus' => $this->session->userdata('kd_bus'),
                        'asal' => $this->session->userdata('asal'),
                        'tujuan' => $this->session->userdata('tujuan')
                );
        
        $data['tiket'] = $this->Admin_model->getKodeTiket($dataKode);
        $data['bus'] = $this->Admin_model->getBus();
        $data['kota'] = $this->Admin_model->getKota();
        $data['kode_awal'] = $this->session->userdata('kode_bus');
        $data['asal_awal'] = $this->session->userdata('asal');
        $data['tujuan_awal'] = $this->session->userdata('tujuan');
        $this->load->view('admin/header');
        $this->load->view('admin/tiket_edit', $data);
    }

    function editDataTiket(){
        $dataEdit = array(
            'kd_tiket' => $this->input->post('kodetiket'),
            'kd_bus' => $this->input->post('kodebus'),
            'nama_tiket' => $this->input->post('namatiket'),
            'asal' => $this->input->post('asal'),
            'tujuan' => $this->input->post('tujuan'),
            'tgl' => $this->input->post('tgl'),
            'jam' => $this->input->post('jam'),
            'harga' => $this->input->post('harga'),
            'sisa_tiket' => $this->input->post('sisa_tiket'),
        );
        
        $this->session->set_userdata(
        $data = array(
                        'kd_tiket' => $this->input->post('kodetiket'),
                        'kd_bus' => $this->input->post('kodebus'),
                        'asal' => $this->input->post('asal'),
                        'tujuan' => $this->input->post('tujuan'),
            )
        );

    }

    public function updateTiket()
    {

        
        $dataUpdate = array(
            'kd_tiket' => $this->input->post('kd_tiket'),
            'kd_bus' => $this->input->post('kd_bus'),
            'asal' => $this->input->post('asal'),
            'tujuan' => $this->input->post('tujuan'),
            'tgl' => $this->input->post('tgl'),
            'jam' => $this->input->post('jam'),
            'harga' => $this->input->post('harga'),
            'sisa_tiket' => $this->input->post('sisa_tiket'),
        );

        $kode = $this->session->userdata('kd_tiket');
        $this->db->where('kd_tiket', $kode);
        $this->db->update('tiket', $dataUpdate);
        
        redirect(base_url('Admin/Menutiket'));    
    }

    public function addTiket(){
        $data['kota'] = $this->Admin_model->getKota();
        $data['bus'] = $this->Admin_model->getBus();
        $this->load->view('admin/header');
        $this->load->view('admin/tambah_tiket',$data);
    }

    public function tambahTiket()
    {
        $add = array(
            'kd_tiket' => $this->input->post('kd_tiket'),
            'kd_bus' => $this->input->post('kd_bus'),
            'asal' => $this->input->post('asal'),
            'tujuan' => $this->input->post('tujuan'),
            'tgl' => $this->input->post('tgl'),
            'jam' => $this->input->post('jam'),
            'harga' => $this->input->post('harga'),
            'sisa_tiket' => $this->input->post('sisa_tiket'),
        );

        $data = $this->Admin_model->addTiket($add);
        redirect(base_url('Admin/Menutiket'));
    }    

     public function addbus(){
        $data['kota'] = $this->Admin_model->getKota();
        $data['bus'] = $this->Admin_model->getBus();
        $this->load->view('admin/header');
        $this->load->view('admin/tambah_bus',$data);
    }

    public function tambahbus()
    {
        $add = array(
            'kd_bus' => $this->input->post('kd_bus'),
            'nama_bus' => $this->input->post('nama_bus'),
            'kapasitas' => $this->input->post('kapasitas')
        );

        $data = $this->Admin_model->addBus($add);
        redirect(base_url('Admin/Menubis'));
    }    

    function hapusBus(){
        $dataCari = array(
            'kd_bus' => $this->input->post('kd_bus')
        );
        $data = $this->Admin_model->deletebus($dataCari);
        echo json_encode($data);

    }


    function geteditbus()
    {
         $dataEdit = array(
            'kd_bus' => $this->input->post('kd_bus')
        );
        
        $this->session->set_userdata(
        $data = array(
            'kd_bus' => $this->input->post('kd_bus')
            )
        );
        print_r($data);
    }

     function editbus(){

        $dataKode = array(
                        'kd_bus' => $this->session->userdata('kd_bus')
                );
        
        $data['bus'] = $this->Admin_model->getKodeBus($dataKode);
        $this->load->view('admin/header');
        $this->load->view('admin/bus_edit', $data);
    }

    public function updateBus()
    {

        $kode = $this->session->userdata('kd_bus');
        $dataUpdate = array(
            'nama_bus' => $this->input->post('nama_bus'),
            'kapasitas' => $this->input->post('kapasitas'),
            'kd_bus' => $this->input->post('kd_bus'),

        );

        
        $this->db->where('kd_bus', $kode);
        $this->db->update('bus', $dataUpdate);
        
        redirect(base_url('Admin/Menubis'));    
    }

}
