<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bus extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bus_model');
    } 

    /*
     * Listing of bus
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('bus/index?');
        $config['total_rows'] = $this->Bus_model->get_all_bus_count();
        $this->pagination->initialize($config);

        $data['bus'] = $this->Bus_model->get_all_bus($params);
        
        $data['_view'] = 'bus/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new bus
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_bus','Nama Bus','max_length[20]');
		$this->form_validation->set_rules('kapasitas','Kapasitas','max_length[2]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama_bus' => $this->input->post('nama_bus'),
				'kapasitas' => $this->input->post('kapasitas'),
            );
            
            $bus_id = $this->Bus_model->add_bus($params);
            redirect('bus/index');
        }
        else
        {            
            $data['_view'] = 'bus/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a bus
     */
    function edit($kd_bus)
    {   
        // check if the bus exists before trying to edit it
        $data['bus'] = $this->Bus_model->get_bus($kd_bus);
        
        if(isset($data['bus']['kd_bus']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama_bus','Nama Bus','max_length[20]');
			$this->form_validation->set_rules('kapasitas','Kapasitas','max_length[2]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama_bus' => $this->input->post('nama_bus'),
					'kapasitas' => $this->input->post('kapasitas'),
                );

                $this->Bus_model->update_bus($kd_bus,$params);            
                redirect('bus/index');
            }
            else
            {
                $data['_view'] = 'bus/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The bus you are trying to edit does not exist.');
    } 

    /*
     * Deleting bus
     */
    function remove($kd_bus)
    {
        $bus = $this->Bus_model->get_bus($kd_bus);

        // check if the bus exists before trying to delete it
        if(isset($bus['kd_bus']))
        {
            $this->Bus_model->delete_bus($kd_bus);
            redirect('bus/index');
        }
        else
            show_error('The bus you are trying to delete does not exist.');
    }
    
}
