<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kota extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kota_model');
    } 

    /*
     * Listing of kota
     */
    function index()
    {
        $data['kota'] = $this->Kota_model->get_all_kota();
        
        $data['_view'] = 'kota/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new kota
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_kota','Nama Kota','required|max_length[255]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama_kota' => $this->input->post('nama_kota'),
            );
            
            $kota_id = $this->Kota_model->add_kota($params);
            redirect('kota/index');
        }
        else
        {            
            $data['_view'] = 'kota/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a kota
     */
    function edit($id_kota)
    {   
        // check if the kota exists before trying to edit it
        $data['kota'] = $this->Kota_model->get_kota($id_kota);
        
        if(isset($data['kota']['id_kota']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama_kota','Nama Kota','required|max_length[255]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama_kota' => $this->input->post('nama_kota'),
                );

                $this->Kota_model->update_kota($id_kota,$params);            
                redirect('kota/index');
            }
            else
            {
                $data['_view'] = 'kota/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The kota you are trying to edit does not exist.');
    } 

    /*
     * Deleting kota
     */
    function remove($id_kota)
    {
        $kota = $this->Kota_model->get_kota($id_kota);

        // check if the kota exists before trying to delete it
        if(isset($kota['id_kota']))
        {
            $this->Kota_model->delete_kota($id_kota);
            redirect('kota/index');
        }
        else
            show_error('The kota you are trying to delete does not exist.');
    }
    
}
