<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tiket extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tiket_model');
    } 

    /*
     * Listing of tiket
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tiket/index?');
        $config['total_rows'] = $this->Tiket_model->get_all_tiket_count();
        $this->pagination->initialize($config);

        $data['tiket'] = $this->Tiket_model->get_all_tiket($params);
        
        $data['_view'] = 'tiket/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tiket
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('asal','Asal','max_length[255]');
		$this->form_validation->set_rules('tujuan','Tujuan','max_length[255]');
		$this->form_validation->set_rules('harga','Harga','integer');
		$this->form_validation->set_rules('stock','Stock','integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'kd_bus' => $this->input->post('kd_bus'),
				'tgl' => $this->input->post('tgl'),
				'asal' => $this->input->post('asal'),
				'tujuan' => $this->input->post('tujuan'),
				'harga' => $this->input->post('harga'),
				'stock' => $this->input->post('stock'),
            );
            
            $tiket_id = $this->Tiket_model->add_tiket($params);
            redirect('tiket/index');
        }
        else
        {            
            $data['_view'] = 'tiket/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tiket
     */
    function edit($kd_tiket)
    {   
        // check if the tiket exists before trying to edit it
        $data['tiket'] = $this->Tiket_model->get_tiket($kd_tiket);
        
        if(isset($data['tiket']['kd_tiket']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('asal','Asal','max_length[255]');
			$this->form_validation->set_rules('tujuan','Tujuan','max_length[255]');
			$this->form_validation->set_rules('harga','Harga','integer');
			$this->form_validation->set_rules('stock','Stock','integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'kd_bus' => $this->input->post('kd_bus'),
					'tgl' => $this->input->post('tgl'),
					'asal' => $this->input->post('asal'),
					'tujuan' => $this->input->post('tujuan'),
					'harga' => $this->input->post('harga'),
					'stock' => $this->input->post('stock'),
                );

                $this->Tiket_model->update_tiket($kd_tiket,$params);            
                redirect('tiket/index');
            }
            else
            {
                $data['_view'] = 'tiket/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tiket you are trying to edit does not exist.');
    } 

    /*
     * Deleting tiket
     */
    function remove($kd_tiket)
    {
        $tiket = $this->Tiket_model->get_tiket($kd_tiket);

        // check if the tiket exists before trying to delete it
        if(isset($tiket['kd_tiket']))
        {
            $this->Tiket_model->delete_tiket($kd_tiket);
            redirect('tiket/index');
        }
        else
            show_error('The tiket you are trying to delete does not exist.');
    }
    
}
