<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tiket extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tiket_model');
    } 

    /*
     * Listing of tiket
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tiket/index?');
        $config['total_rows'] = $this->Tiket_model->get_all_tiket_count();
        $this->pagination->initialize($config);

        $data['tiket'] = $this->Tiket_model->get_all_tiket($params);
        
        $data['_view'] = 'tiket/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tiket
     */
   

    /*
     * Editing a tiket
     */
    
    
}
