<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bus_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bus by kd_bus
     */
    function get_bus($kd_bus)
    {
        return $this->db->get_where('bus',array('kd_bus'=>$kd_bus))->row_array();
    }
    
    /*
     * Get all bus count
     */
    function get_all_bus_count()
    {
        $this->db->from('bus');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all bus
     */
    function get_all_bus($params = array())
    {
        $this->db->order_by('kd_bus', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('bus')->result_array();
    }
        
    /*
     * function to add new bus
     */
    function add_bus($params)
    {
        $this->db->insert('bus',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bus
     */
    function update_bus($kd_bus,$params)
    {
        $this->db->where('kd_bus',$kd_bus);
        return $this->db->update('bus',$params);
    }
    
    /*
     * function to delete bus
     */
    function delete_bus($kd_bus)
    {
        return $this->db->delete('bus',array('kd_bus'=>$kd_bus));
    }
}
