<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kota_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kota by id_kota
     */
    function get_kota($id_kota)
    {
        return $this->db->get_where('kota',array('id_kota'=>$id_kota))->row_array();
    }
        
    /*
     * Get all kota
     */
    function get_all_kota()
    {
        $this->db->order_by('id_kota', 'desc');
        return $this->db->get('kota')->result_array();
    }
        
    /*
     * function to add new kota
     */
    function add_kota($params)
    {
        $this->db->insert('kota',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update kota
     */
    function update_kota($id_kota,$params)
    {
        $this->db->where('id_kota',$id_kota);
        return $this->db->update('kota',$params);
    }
    
    /*
     * function to delete kota
     */
    function delete_kota($id_kota)
    {
        return $this->db->delete('kota',array('id_kota'=>$id_kota));
    }
}
