<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tiket_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tiket by kd_tiket
     */
    function get_tiket($kd_tiket)
    {
        return $this->db->get_where('tiket',array('kd_tiket'=>$kd_tiket))->row_array();
    }
    
    function get_Tiketjoin()
        {

            $this->db->select('kd_tiket, kd_bus, tgl, jam, k1.`nama_kota` AS asal, k2.`nama_kota` AS tujuan, harga, stock');
            $this->db->from('tiket');
            $this->db->join('kota k1', 'tiket.asal = k1.id_kota');
            $this->db->join('kota k2', 'tiket.tujuan = k2.id_kota');
            $this->db->order_by('kd_tiket', 'ASC');
            $query = $this->db->get();
            return $query->result_array();

        }

    /*
     * Get all tiket count
     */
    function get_all_tiket_count()
    {
        $this->db->from('tiket');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tiket
     */
    function get_all_tiket($params = array())
    {
        $this->db->order_by('kd_tiket', 'asc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tiket')->result_array();
    }
        
    /*
     * function to add new tiket
     */
    function add_tiket($params)
    {
        $this->db->insert('tiket',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tiket
     */
    function update_tiket($kd_tiket,$params)
    {
        $this->db->where('kd_tiket',$kd_tiket);
        return $this->db->update('tiket',$params);
    }
    
    /*
     * function to delete tiket
     */
    function delete_tiket($kd_tiket)
    {
        return $this->db->delete('tiket',array('kd_tiket'=>$kd_tiket));
    }

    function found_tiket($datacari)
    {
            $this->db->select('kd_tiket, kd_bus, tgl, jam, k1.`nama_kota` AS asal, k2.`nama_kota` AS tujuan, harga, stock');
            $this->db->from('tiket');
            $this->db->join('kota k1', 'tiket.asal = k1.id_kota');
            $this->db->join('kota k2', 'tiket.tujuan = k2.id_kota');
            $this->db->where('k1.nama_kota', $datacari['asal']);
            $this->db->where('k2.nama_kota', $datacari['tujuan']);
            $this->db->order_by('kd_tiket', 'ASC');
            $query = $this->db->get();
            return $query->result_array();
    }
}
